# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bayes < Formula
  desc "CLI command-line tools for OpenBayes console"
  homepage "https://openbayes.com"
  version "0.14.3"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/signcl/bayes-releases/releases/download/v0.14.3/bayes_darwin_arm64.zip"
      sha256 "ea4c06b824613dd403d42b4c28690c68d02b04ff683217b8ff7869f25f89e343"

      def install
        bin.install "bayes"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/signcl/bayes-releases/releases/download/v0.14.3/bayes_darwin_amd64.zip"
      sha256 "3f64b42d9f27c01237ef116e6abb3d18e85c254a6499e02deb10f658d07f9a43"

      def install
        bin.install "bayes"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/signcl/bayes-releases/releases/download/v0.14.3/bayes_linux_arm64.zip"
      sha256 "95be3d8894709522d9d9dc3ce50c26e25bf96d4aa56e94aebea942e0ee1a5066"

      def install
        bin.install "bayes"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/signcl/bayes-releases/releases/download/v0.14.3/bayes_linux_arm.zip"
      sha256 "1827c904d5c5bc8dd868786dc504bd8fb4a1ce4f5c65d2a2dcf6821c90ba7062"

      def install
        bin.install "bayes"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/signcl/bayes-releases/releases/download/v0.14.3/bayes_linux_amd64.zip"
      sha256 "fb4f2f9f375caf99e3e8c73bd93c51ff284e760f9a2a38b24cdf134f461b5ac7"

      def install
        bin.install "bayes"
      end
    end
  end

  test do
    system "#{bin}/bayes -v"
  end
end
